language: node_js
node_js:
  - 14.8.0
install: npm install && npm audit fix

env:


#before_script:
#  - if [ $TRAVIS_BRANCH == "master" ]; then
#      sudo aws s3 rm s3://noahvarghese.me/ --recursive;
#    elif [ $TRAVIS_BRANCH == "test" ]; then
#      sudo aws s3 rm s3://test.noahvarghese.me/ --recursive;
#    fi

script: gatsby clean && gatsby build

#after_script: pwd && ls -la;

#before_deploy: pwd && ls -la

# safelist
branches:
  only:
  - master
  - test
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: 
    - if [ $TRAVIS_BRANCH = "master ]; then
        noahvarghese.me
      elif
        test.noahvarghese.me
      fi
  acl: public_read
  region: ca-central-1
  cleanup: true
  local_dir: ./public


#after_deploy: 
#  - if [ $TRAVIS_BRANCH == "master" ]; then
#      sudo aws s3 rm s3://noahvarghese.me/src --recursive;
#    elif [ $TRAVIS_BRANCH == "test" ]; then
#      sudo aws s3 rm s3://test.noahvarghese.me/src --recursive;
#    fi
  