language: node_js
node_js:
  - 14.8.0
install: npm install && npm audit fix
script: gatsby build
# safelist
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: 'noahvarghese.me'
  endpoint: http://noahvarghese.me.s3-website.ca-central-1.amazonaws.com/
  acl: public_read
  