language: node_js
node_js:
  - 14.8.0
install: npm i
script: gatsby build
branches:
  only:
    - master
deploy:
  provider: s3
  accesss_key_id:
    secure: nqJY2Qc+4IwCc7IdbMhfwdzQiwkcnMqKgn45U+rBPg8DRHd/v8Xd6sd05vXiRCxmtV2DB3aU3aM5PfnJFpgSVG+yDSW+rySe+77XLzIe9O/urIQy4gXc+68jKXYsHVIPyRgjOPhMO7d5toaMOdHPHTXt7myGNw1e7ITcJCnSuK4TY+q3pxTL5rOMxS3FR2qOE/Uwt3pedG9iPhWJem1WZtwmb/mfUW6cql7RbT8paD7CC4QbVuDqUwl7TMBbuWlGIipsKnukTDPma/2SvzU6CBYy1nkwpvQ1IipR9EtinC2I+OPUPObDUGNsUFFXxLZGpYhP+EVRdhOTObQhTe/VRDRbCGsovvFRuMLaCG3Jhi691Za20LpFFKgVL7k54sfKh+DDnL6WdESvskeH+aH2vnm7CBW3zPJ+2zFqo93YdJMCnbYxP2b6VlT+vnUnCxRih7JhkKAe9j6srRtH6J1zw0qp1HUmFSEj4nIFNy+eIKiekU3tvl46cMdedo23b7yVJaBl7frl7eDeFLN/po0YqY0JUwLPXLD3G70hXoLH36qyZIN2oR24PyM6iRD+5bTOGe/3lVm+CzS69L/QLHVaB8k3nGVOS0FWJYKE5SrT0mXqOtybxiBo06cY91vD8LwqC66IjtDCUW2XsqErU5YvqI4qji2xOkai4jZPjNCsEno=
  secret_access_key:
    secure: N3+6r9FjJ2DCLA+m9Qg6n7F1rKBaTjuCnZyqdKn/ZmN9g1k+yI/kHicCe9zFmojQyTH4jz6esWxuhl74iRcosDszOwM2mXrJAVMBVhwQCRdvkF2/gdfTm4yNtymVZwCVU87zWftN4OW7uUfHZIqNoswRMnHH27o1D6xzSHHQ8MpCJI7DkqsWB8adaDNRXwQkBL/NqXjRI7bWe0xevAAIQoB+TmU/B4w7XETdg8JRd69OKxxsveSRAyAmgezmrXA+NxSzLY53JDJP1hX99hTqUNq24/UtLDHNHNlh+0plEs78psTVeugzX0Y3hA/DAb/azGE5yXS5c/R274qzWga8yDE6gThrxzaMuY8hV6tPEtwlnh9Ppo3maNmjk6b2ech4PfPWCuiPhLFxxqfzt2LjcOj9wW39w8RahsqZq77qMTz3+81MA1/iacro1ymiaMkMfE+xTBTE5cPnMEOfBqNtJSY1h8odMigAkUGktVvX29MnklpUsLjBrps+7q3aE6MFcXMk4tRhxuTEPhIYyqEzhPn6vbsS0FxEJaBHBmNtxWeEMTAw95rA0I7J/HzbbzYEIsl808MFp7fbwbh/9ykgRGjigjkBNJlk6oEgAY38MB4nUZ61l43KTawf8hdcLt05mxsLeMivmHLSsD6FdTrVSWsKbLml7C+azgxS+j6thBs=
  bucket: "noah-portfolio"
  endpoint: http://noah-portfolio.s3-website.ca-central-1.amazonaws.com
  skip_cleanup: true
  acl: public_read
  local_dir: public
