language: node_js
node_js:
  - 14.8.0
install: npm install && npm audit fix

before_script:
  - if [ $TRAVIS_BRANCH == "master" ];then
      echo $TRAVIS_BRANCH;
    elif [ $TRAVIS_BRANCH == "test" ]; then
      echo $TRAVIS_BRANCH;
    fi

script: gatsby build
# safelist
branches:
  only:
  - master
  - test
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: noahvarghese.me
  acl: public_read
  region: ca-central-1
  on: 
    branch: master
  provider: s3 
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: test.noahvarghese.me
  acl: public_read
  region: ca-central-1
  on:
    branch: test
  